name: TestUtilities
version: 0.1
main: com.github.paradiddle.testingutils.TestUtilities
commands:
  binfo:
    description: This command lists information about a block at a certain location.
    usage: /binfo [x] [y] [z] [world_name]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  binfo:
    description: This command toggles the crouch looking at block.
    usage: /binfo [true/false]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  worlds:
    description: This command lists all world names
    usage: /worlds
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  floor:
    description: This command allows you to easily build a floor.
    usage: /floor (look at wall block)
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  wall:
    description: This command allows you to easily build a wall.
    usage: /wall (look at wall block)
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  coords:
    description: This command brodcasts your coordinates.
    usage: /coords
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  snowbgone:
    description: This command removes snow in a large area around the player.
    usage: /snowbgone
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
